### ISSUE TITLE
Risk should have type object

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/ocds-riskAllocation-extension#1]

**Comment by duncandewhurst** [comment]
Fixed in this [commit](https://github.com/open-contracting/ocds-riskAllocation-extension/commit/98446c61a1c43c08413e0ce19ef61498864d804e)

**Comment by Bjwebb** [comment]
This isn't fixed in the versioned release schema patch, although that's not a problem for what I'm doing with flatten-tool.

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/standard/issues/517
