### ISSUE TITLE
How is versioned-release-validation-schema.json generated in extensions?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-riskAllocation-extension#7]
I was wondering why its `Risk.category` `enum` wasn't using the codelist, when I realized that it was out of sync.

**Comment by timgdavies** [comment]
I don't think we have a set method for this right now - and I've not been generating them - as I think there is a wider outstanding issue about automatic generation of versioned-release-validation-schema (and whether or not it is actually being used anywhere...)

**Comment by jpmckinney** [comment]
Aha. Where can I catch up on that issue?

**Comment by timgdavies** [comment]
It was last discussed in a GitHub issue here: https://github.com/open-contracting/standard/issues/146

It's been discussed in person a few times, but perhaps one to re-open on GitHub / bring up in tech planning.
